backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Privacy Policy"
        name: "privacy"
        file: "src/content/privacy.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Effective Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
