backend:
  name: git-gateway
  branch: main
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Privacy Policy"
        name: "privacy"
        file: "content/privacy.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Terms & Conditions"
        name: "terms"
        file: "content/terms.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
