backend:
  name: git-gateway
  branch: main

site_url: https://example.com

publish_mode: editorial_workflow
media_folder: public/uploads
public_folder: /uploads

collections:
  - name: settings
    label: Settings
    files:
      - name: general
        label: Site Settings
        file: src/content/settings.json
        fields:
          - { label: "Site Title", name: "site_title", widget: "string" }
          - { label: "Default Author", name: "author", widget: "string" }
          - {
              label: "Posts Per Page",
              name: "posts_per_page",
              widget: "number",
              min: 1,
              max: 20,
            }

  - name: pages
    label: Pages
    folder: src/content/pages
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: posts
    label: Posts
    folder: src/content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD HH:mm",
          default: "{{now}}",
        }
      - {
          label: "Cover Image",
          name: "image",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: faq
    label: FAQ
    folder: src/content/faq
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Question", name: "question", widget: "string" }
      - { label: "Answer", name: "answer", widget: "markdown" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD HH:mm",
          default: "{{now}}",
        }

  - name: features
    label: Features
    folder: src/content/features
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Icon", name: "icon", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "markdown" }

  - name: fees
    label: Fees
    folder: src/content/fees
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Type",
          name: "type",
          widget: "select",
          options: ["percentage", "fixed"],
        }
      - {
          label: "Amount",
          name: "amount",
          widget: "number",
          value_type: "float",
          min: 0,
        }
      - {
          label: "Currency",
          name: "currency",
          widget: "string",
          default: "USD",
        }
      - {
          label: "Description",
          name: "description",
          widget: "markdown",
          required: false,
        }
      - { label: "Active", name: "active", widget: "boolean", default: true }

  - name: integrations
    label: Integrations
    folder: src/content/integrations
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Link", name: "link", widget: "string", required: false }

  - name: testimonials
    label: Testimonials
    folder: src/content/testimonials
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string", required: false }
      - { label: "Company", name: "company", widget: "string", required: false }
      - { label: "Photo", name: "photo", widget: "image", required: false }
      - { label: "Testimonial", name: "testimonial", widget: "markdown" }

  - name: team
    label: Team Members
    folder: src/content/team
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image", required: false }
      - { label: "Bio", name: "bio", widget: "markdown" }

  - name: changelog
    label: Changelog
    folder: src/content/changelog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD HH:mm",
          default: "{{now}}",
        }
      - { label: "Changes", name: "changes", widget: "markdown" }

  - name: privacy
    label: Privacy Policy
    files:
      - label: "Privacy Policy"
        name: privacy
        file: src/content/privacy.md
        fields:
          - {
              label: "Title",
              name: "title",
              widget: "string",
              default: "Privacy Policy",
            }
          - {
              label: "Date",
              name: "date",
              widget: "datetime",
              format: "YYYY-MM-DD HH:mm",
              default: "{{now}}",
            }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: terms
    label: Terms & Conditions
    files:
      - label: "Terms & Conditions"
        name: terms
        file: src/content/terms.md
        fields:
          - {
              label: "Title",
              name: "title",
              widget: "string",
              default: "Terms & Conditions",
            }
          - {
              label: "Date",
              name: "date",
              widget: "datetime",
              format: "YYYY-MM-DD HH:mm",
              default: "{{now}}",
            }
          - { label: "Body", name: "body", widget: "markdown" }
